export const GIAO_XU = [
  {
    col: [
      {
        name: 'Tên giáo phận:',
        type: 'text',
        icon: 'user',
        required: 'true',
        errMess: 'Vui lòng nhập tên giáo phận',
        placeholder: 'Nhập tên giáo phận',
        column: 12,
      },
      {
        name: 'Tên giáo hạt:',
        type: 'text',
        icon: 'user',
        required: 'true',
        errMess: 'Vui lòng nhập tên giáo hạt',
        placeholder: 'Nhập tên giáo hạt',
        column: 12,
      },
      {
        name: 'Tên giáo xứ:',
        type: 'text',
        icon: 'user',
        required: 'true',
        errMess: 'Vui lòng nhập tên giáo xứ',
        placeholder: 'Nhập tên giáo xứ',
        column: 12,
      },
      {
        name: 'Địa chỉ:',
        type: 'text',
        icon: 'user',
        required: 'true',
        errMess: 'Vui lòng nhập địa chỉ',
        placeholder: 'Nhập tên địa chỉ',
        column: 12,
      },
      {
        name: 'Website:',
        type: 'text',
        icon: 'user',
        required: 'false',
        errMess: 'Vui lòng nhập website',
        placeholder: 'Nhập website',
        column: 12,
      },
      {
        name: 'Số điện thoại:',
        type: 'text',
        icon: 'user',
        required: 'true',
        errMess: 'Vui lòng nhập số điện thoại',
        placeholder: 'Nhập số điện thoại',
        column: 12,
      },
      {
        name: 'Email:',
        type: 'text',
        icon: 'user',
        required: 'false',
        errMess: 'Vui lòng nhập email',
        placeholder: 'Nhập email',
        column: 12,
      },
      {
        name: 'Hình giáo xứ:',
        type: 'images',
        icon: 'user',
        required: 'false',
        errMess: '',
      },
    ],
  },
  {
    col: [
      {
        name: 'Ghi chú:',
        type: 'textarea',
        // icon: 'user',
        required: 'false',
        errMess: 'Vui lòng nhập Ghi chu',
        placeholder: 'Nhập Ghi chú',
        column: 24,
      },
    ],
  },
];
